services:
  db:
    image: postgres:15
    container_name: aluep-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    command: >
      bash -c "
      apt-get update && apt-get install -y locales &&
      localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8 &&
      /usr/local/bin/docker-entrypoint.sh postgres
      "
  gcs:
    image: fsouza/fake-gcs-server
    volumes:
      - ./local-gcs:/data/aluep-user-upload
    ports:
      - 4443:4443
    command: -scheme http -public-host localhost:4443
