name: "deploy-to-cloudrun"

on:
  push:
    branches:
      - "main"

env:
  TZ: Asia/Tokyo
  IMAGE_REPOSITORY_NAME: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aluep
  IMAGE_NAME: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aluep/aluep:${{ github.sha }}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3"

      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "Configure docker to use the gcloud cli"
        run: gcloud auth configure-docker --quiet asia-northeast1-docker.pkg.dev

      - name: "Database migration"
        run: npx prisma migrate deploy

      # seedを実行するための環境をインストールする
      - name: "Set up ts-node"
        run: npm install typescript ts-node

      - name: "Detabase seeding"
        run: npx prisma db seed

      - name: "Build docker image"
        run: >
          docker build
          -t ${{ env.IMAGE_NAME }}
          --build-arg NEXT_PUBLIC_URL=${{ vars.NEXT_PUBLIC_URL }}
          --build-arg NEXT_PUBLIC_CONTACT_URL=${{ vars.NEXT_PUBLIC_CONTACT_URL }}
          --build-arg NEXT_PUBLIC_RECAPTCHA_KEY=${{ vars.NEXT_PUBLIC_RECAPTCHA_KEY }}
          .

      - name: "Push docker image"
        run: docker push ${{ env.IMAGE_NAME }}

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "aluep"
          image: ${{ env.IMAGE_NAME }}
          region: ${{ secrets.CLOUDRUN_REGION }}

      - name: "Remove docker image"
        uses: "docker://asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli"
        with:
          # gcr-cleaner-cliが内部でUTC使ってるせいで、日本にあるArtifact Registryと9時間ずれるから、
          # 9時間経ってないイメージは消せないけど、どうしようもなさそうだから妥協する
          # 9時間の間に何回もデプロイすることなんてないでしょ多分・・・
          args: >
            -repo=${{ env.IMAGE_REPOSITORY_NAME }}
            -tag-filter-any=.*
